# Generated by Django 4.2.6 on 2023-11-14 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Services",
            fields=[
                ("service_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "service_option",
                    models.CharField(
                        choices=[
                            ("Cosmetic Dentistry", "Cosmetic Dentistry"),
                            ("Dental Implant", "Dental Implant"),
                            ("Dental Bridges", "Dental Bridges"),
                            ("Teeth Whitening", "Teeth Whitening"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "service_logo",
                    models.ImageField(blank=True, null=True, upload_to="service_logo/"),
                ),
                ("price", models.BigIntegerField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "HoD",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
