# Generated by Django 4.2.6 on 2023-11-16 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("serviceapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book_service",
            fields=[
                ("booking_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "service_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_created", models.DateField(auto_now_add=True)),
                ("payment", models.BooleanField(blank=True, default=False, null=True)),
                ("price", models.BigIntegerField(default=0)),
                (
                    "hod",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hod",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="serviceapp.services",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
