# Generated by Django 4.2.6 on 2023-11-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book_appointment",
            fields=[
                ("appointment_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Emergency", "Emergency"),
                            ("Operation & Surgery", "Operation & Surgery"),
                            ("Outdoor Checkup", "Outdoor Checkup"),
                            ("Ambulance Service", "Ambulance Service"),
                            ("Medicine & Pharmacy", "Medicine & Pharmacy"),
                            ("Medical Lab", "Medical Lab"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("appointment_date", models.DateField(blank=True, null=True)),
                ("appointment_time", models.TimeField(blank=True, null=True)),
                ("client_name", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "client_email",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("approved_date", models.DateField(blank=True, null=True)),
                ("approved_time", models.TimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Declined", "Declined"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
